/*
 * Copyright (C) 2019  Consiglio Nazionale delle Ricerche
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public License
 *     along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.14 at 03:35:52 PM CET 
//


package it.cnr.si.siopeplus;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import it.siopeplus.CtEsitoMandati;
import it.siopeplus.CtEsitoReversali;
import it.siopeplus.CtTestataMessaggio;
import it.siopeplus.SignatureType;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.*;
import org.jvnet.jaxb.lang.JAXBToStringStrategy;
import org.jvnet.jaxb.lang.ToString;
import org.jvnet.jaxb.lang.ToStringStrategy;
import org.jvnet.jaxb.locator.ObjectLocator;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="testata_messaggio" type="{}ctTestata_messaggio"/&gt;
 *         &lt;element name="identificativo_flusso_BT" type="{http://www.w3.org/2001/XMLSchema}anyType"/&gt;
 *         &lt;choice maxOccurs="unbounded"&gt;
 *           &lt;element name="esito_reversali" type="{}ctEsito_reversali"/&gt;
 *           &lt;element name="esito_mandati" type="{}ctEsito_mandati"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="Id" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testataMessaggio",
    "identificativoFlussoBT",
    "esitoReversaliOrEsitoMandati",
    "signature"
})
@XmlRootElement(name = "messaggi_esito_applicativo")
public class MessaggiEsitoApplicativo implements Serializable, ToString
{

    @XmlElement(name = "testata_messaggio", required = true)
    protected CtTestataMessaggio testataMessaggio;
    @XmlElement(name = "identificativo_flusso_BT", required = true)
    protected Object identificativoFlussoBT;
    @XmlElements({
        @XmlElement(name = "esito_reversali", type = CtEsitoReversali.class),
        @XmlElement(name = "esito_mandati", type = CtEsitoMandati.class)
    })
    protected List<Object> esitoReversaliOrEsitoMandati;
    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#", required = true)
    protected SignatureType signature;
    @XmlAttribute(name = "Id")
    @XmlSchemaType(name = "anySimpleType")
    protected String id;

    /**
     * Gets the value of the testataMessaggio property.
     * 
     * @return
     *     possible object is
     *     {@link CtTestataMessaggio }
     *     
     */
    public CtTestataMessaggio getTestataMessaggio() {
        return testataMessaggio;
    }

    /**
     * Sets the value of the testataMessaggio property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtTestataMessaggio }
     *     
     */
    public void setTestataMessaggio(CtTestataMessaggio value) {
        this.testataMessaggio = value;
    }

    /**
     * Gets the value of the identificativoFlussoBT property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getIdentificativoFlussoBT() {
        return identificativoFlussoBT;
    }

    /**
     * Sets the value of the identificativoFlussoBT property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setIdentificativoFlussoBT(Object value) {
        this.identificativoFlussoBT = value;
    }

    /**
     * Gets the value of the esitoReversaliOrEsitoMandati property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the esitoReversaliOrEsitoMandati property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEsitoReversaliOrEsitoMandati().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtEsitoReversali }
     * {@link CtEsitoMandati }
     * 
     * 
     */
    public List<Object> getEsitoReversaliOrEsitoMandati() {
        if (esitoReversaliOrEsitoMandati == null) {
            esitoReversaliOrEsitoMandati = new ArrayList<Object>();
        }
        return this.esitoReversaliOrEsitoMandati;
    }

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    @Override
    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.getInstance();
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    @Override
    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    @Override
    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {

        {
            CtTestataMessaggio theTestataMessaggio;
            theTestataMessaggio = this.getTestataMessaggio();
            strategy.appendField(locator, this, "testataMessaggio", buffer, theTestataMessaggio, (this.testataMessaggio!= null));
        }
        {
            Object theIdentificativoFlussoBT;
            theIdentificativoFlussoBT = this.getIdentificativoFlussoBT();
            strategy.appendField(locator, this, "identificativoFlussoBT", buffer, theIdentificativoFlussoBT, (this.identificativoFlussoBT!= null));
        }
        {
            List<Object> theEsitoReversaliOrEsitoMandati;
            theEsitoReversaliOrEsitoMandati = (((this.esitoReversaliOrEsitoMandati!= null)&&(!this.esitoReversaliOrEsitoMandati.isEmpty()))?this.getEsitoReversaliOrEsitoMandati():null);
            strategy.appendField(locator, this, "esitoReversaliOrEsitoMandati", buffer, theEsitoReversaliOrEsitoMandati, ((this.esitoReversaliOrEsitoMandati!= null)&&(!this.esitoReversaliOrEsitoMandati.isEmpty())));
        }
        {
            SignatureType theSignature;
            theSignature = this.getSignature();
            strategy.appendField(locator, this, "signature", buffer, theSignature, (this.signature!= null));
        }
        {
            String theId;
            theId = this.getId();
            strategy.appendField(locator, this, "id", buffer, theId, (this.id!= null));
        }
        return buffer;
    }

}
